spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:sensors_data}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

metrics:
  masterNode:
    ip: ${MASTER_NODE:192.168.0.101}
  collector:
    name: ${COLLECTOR_NAME:raspberrypi-02}
  location:
    name: ${LOCATION_NAME:smarthome}